/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as DeckBuilderIndexImport } from './routes/deck-builder/index'
import { Route as MatchMatchIdImport } from './routes/match/$matchId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DeckBuilderIndexRoute = DeckBuilderIndexImport.update({
  id: '/deck-builder/',
  path: '/deck-builder/',
  getParentRoute: () => rootRoute,
} as any)

const MatchMatchIdRoute = MatchMatchIdImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/match/$matchId': {
      id: '/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof MatchMatchIdImport
      parentRoute: typeof rootRoute
    }
    '/deck-builder/': {
      id: '/deck-builder/'
      path: '/deck-builder'
      fullPath: '/deck-builder'
      preLoaderRoute: typeof DeckBuilderIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/deck-builder': typeof DeckBuilderIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/deck-builder': typeof DeckBuilderIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/deck-builder/': typeof DeckBuilderIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/match/$matchId' | '/deck-builder'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/match/$matchId' | '/deck-builder'
  id: '__root__' | '/' | '/match/$matchId' | '/deck-builder/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MatchMatchIdRoute: typeof MatchMatchIdRoute
  DeckBuilderIndexRoute: typeof DeckBuilderIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MatchMatchIdRoute: MatchMatchIdRoute,
  DeckBuilderIndexRoute: DeckBuilderIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/match/$matchId",
        "/deck-builder/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/match/$matchId": {
      "filePath": "match/$matchId.tsx"
    },
    "/deck-builder/": {
      "filePath": "deck-builder/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
