/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HowToPlayIndexRouteImport } from './routes/how-to-play/index'
import { Route as DecksIndexRouteImport } from './routes/decks/index'
import { Route as DecksNewRouteImport } from './routes/decks/new'
import { Route as MatchMatchIdIndexRouteImport } from './routes/match/$matchId/index'
import { Route as MatchMatchIdJoinRouteImport } from './routes/match/$matchId/join'
import { Route as DecksDeckIdEditRouteImport } from './routes/decks/$deckId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToPlayIndexRoute = HowToPlayIndexRouteImport.update({
  id: '/how-to-play/',
  path: '/how-to-play/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksIndexRoute = DecksIndexRouteImport.update({
  id: '/decks/',
  path: '/decks/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksNewRoute = DecksNewRouteImport.update({
  id: '/decks/new',
  path: '/decks/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchMatchIdIndexRoute = MatchMatchIdIndexRouteImport.update({
  id: '/match/$matchId/',
  path: '/match/$matchId/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchMatchIdJoinRoute = MatchMatchIdJoinRouteImport.update({
  id: '/match/$matchId/join',
  path: '/match/$matchId/join',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksDeckIdEditRoute = DecksDeckIdEditRouteImport.update({
  id: '/decks/$deckId/edit',
  path: '/decks/$deckId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/decks/new': typeof DecksNewRoute
  '/decks': typeof DecksIndexRoute
  '/how-to-play': typeof HowToPlayIndexRoute
  '/decks/$deckId/edit': typeof DecksDeckIdEditRoute
  '/match/$matchId/join': typeof MatchMatchIdJoinRoute
  '/match/$matchId': typeof MatchMatchIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/decks/new': typeof DecksNewRoute
  '/decks': typeof DecksIndexRoute
  '/how-to-play': typeof HowToPlayIndexRoute
  '/decks/$deckId/edit': typeof DecksDeckIdEditRoute
  '/match/$matchId/join': typeof MatchMatchIdJoinRoute
  '/match/$matchId': typeof MatchMatchIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/decks/new': typeof DecksNewRoute
  '/decks/': typeof DecksIndexRoute
  '/how-to-play/': typeof HowToPlayIndexRoute
  '/decks/$deckId/edit': typeof DecksDeckIdEditRoute
  '/match/$matchId/join': typeof MatchMatchIdJoinRoute
  '/match/$matchId/': typeof MatchMatchIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/decks/new'
    | '/decks'
    | '/how-to-play'
    | '/decks/$deckId/edit'
    | '/match/$matchId/join'
    | '/match/$matchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/decks/new'
    | '/decks'
    | '/how-to-play'
    | '/decks/$deckId/edit'
    | '/match/$matchId/join'
    | '/match/$matchId'
  id:
    | '__root__'
    | '/'
    | '/decks/new'
    | '/decks/'
    | '/how-to-play/'
    | '/decks/$deckId/edit'
    | '/match/$matchId/join'
    | '/match/$matchId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DecksNewRoute: typeof DecksNewRoute
  DecksIndexRoute: typeof DecksIndexRoute
  HowToPlayIndexRoute: typeof HowToPlayIndexRoute
  DecksDeckIdEditRoute: typeof DecksDeckIdEditRoute
  MatchMatchIdJoinRoute: typeof MatchMatchIdJoinRoute
  MatchMatchIdIndexRoute: typeof MatchMatchIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-play/': {
      id: '/how-to-play/'
      path: '/how-to-play'
      fullPath: '/how-to-play'
      preLoaderRoute: typeof HowToPlayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/': {
      id: '/decks/'
      path: '/decks'
      fullPath: '/decks'
      preLoaderRoute: typeof DecksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/new': {
      id: '/decks/new'
      path: '/decks/new'
      fullPath: '/decks/new'
      preLoaderRoute: typeof DecksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$matchId/': {
      id: '/match/$matchId/'
      path: '/match/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof MatchMatchIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$matchId/join': {
      id: '/match/$matchId/join'
      path: '/match/$matchId/join'
      fullPath: '/match/$matchId/join'
      preLoaderRoute: typeof MatchMatchIdJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks/$deckId/edit': {
      id: '/decks/$deckId/edit'
      path: '/decks/$deckId/edit'
      fullPath: '/decks/$deckId/edit'
      preLoaderRoute: typeof DecksDeckIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DecksNewRoute: DecksNewRoute,
  DecksIndexRoute: DecksIndexRoute,
  HowToPlayIndexRoute: HowToPlayIndexRoute,
  DecksDeckIdEditRoute: DecksDeckIdEditRoute,
  MatchMatchIdJoinRoute: MatchMatchIdJoinRoute,
  MatchMatchIdIndexRoute: MatchMatchIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
