name: Built and Test

on:
  push:
    branches: main
  pull_request:
    branches: main,

jobs:
  build-and-test:
    name: Build & Test ${{ matrix.project }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - project: server
            path: apps/server
          - project: web
            path: apps/web

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build ${{ matrix.project }}
        run: bun run --cwd ${{ matrix.path }} build

      - name: Test ${{ matrix.project }}
        run: bun run --cwd ${{ matrix.path }} test
